table 'Price Adjustment (%)'
	lineageTag: de2d54a9-e299-422c-9455-d523b2f588cd

	measure 'Price Adjustment (%) Value' = SELECTEDVALUE('Price Adjustment (%)'[Price Adjustment (%)], 0)
		lineageTag: 853870a8-ba48-4cb5-afd7-668edf62f2cb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Price Adjustment (%)'
		lineageTag: 89570628-2766-4180-89e5-60547511c44f
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Price Adjustment (%)' = calculated
		mode: import
		source = GENERATESERIES(-1, 1, 0.1)

	annotation PBI_Id = 92aa1da5cc03463ba0bfa95484292439

